[tool.ruff]
exclude = [
    "venv",
    ".git",
    ".mypy_cache",
    "recordings",
    "migrations",
]
line-length = 120

[tool.ruff.pycodestyle]
max-doc-length = 120


[tool.black]
extend-exclude = "migrations"
force-exclude = "migrations"
skip-string-normalization = 1
line-length = 88


[tool.isort]
profile = "black"
extend_skip = "migrations, models/__init__.py"


[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "timings.settings"
# -- recommended but optional:
python_files = ["test_*.py", "*_test.py", "tests/*.py"]
