[tool.ruff]
exclude = [
    "venv",
    ".git",
    ".mypy_cache",
    "recordings",
    "migrations",
]
line-length = 120

[tool.ruff.pycodestyle]
max-doc-length = 120


[tool.black]
extend-exclude = "migrations"
skip-string-normalization = 1
line-length = 88


[tool.isort]
profile = "hug"
extend_skip = "migrations"