# Generated by Django 4.0.6 on 2023-06-08 19:24

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StintInfo',
            fields=[
                ('stint_id', models.TextField(primary_key=True, serialize=False)),
                ('pilot', models.TextField()),
                ('stint', models.IntegerField()),
                ('kart', models.IntegerField()),
                ('stint_started_at', models.IntegerField()),
                ('laps_amount', models.IntegerField()),
                ('lap_times', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('best_lap', models.FloatField()),
                ('best_sector_1', models.FloatField()),
                ('best_sector_2', models.FloatField()),
                ('best_theoretical', models.FloatField()),
                ('avg_80', models.FloatField()),
            ],
            options={
                'db_table': 'stints_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BoardRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('url', models.TextField()),
                ('response_status', models.IntegerField()),
                ('response_body', models.TextField()),
                ('response_json', models.JSONField(default=None)),
                ('resolution', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'requests',
            },
        ),
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('team', models.IntegerField()),
                ('pilot_name', models.TextField()),
                ('kart_raw', models.IntegerField()),
                ('kart', models.IntegerField()),
                ('race_time', models.IntegerField()),
                ('ontrack', models.FloatField()),
                ('stint', models.IntegerField()),
                ('lap_number', models.IntegerField()),
                ('lap_time', models.FloatField()),
                ('sector_1', models.FloatField(null=True)),
                ('sector_2', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'laps',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(default='https://nfs-stats.herokuapp.com/getmaininfo.json')),
                ('created_at', models.DateTimeField()),
                ('name', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'races',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='stats.race')),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.AddConstraint(
            model_name='race',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='races_single_active'),
        ),
        migrations.AddField(
            model_name='lap',
            name='board_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laps', to='stats.boardrequest'),
        ),
        migrations.AddField(
            model_name='lap',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laps', to='stats.race'),
        ),
        migrations.AddField(
            model_name='boardrequest',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stats.race', verbose_name='requests'),
        ),
    ]
