# Generated by Django 4.0.6 on 2022-07-07 23:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StintInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilot', models.TextField()),
                ('team_number', models.IntegerField()),
                ('stint', models.IntegerField()),
                ('kart', models.IntegerField()),
                ('laps_amount', models.IntegerField()),
                ('lap_times', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('avg_80', models.FloatField()),
                ('avg_40', models.FloatField()),
            ],
            options={
                'db_table': 'stints_info',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """   
            create materialized view stints_info as (
            
            with stints as (select string_agg(distinct pilot_name, ' OR ') as pilot,
                                   team_number,
                                   stint,
                                   kart,
                                   count(*)                       as laps_amount,
                                   min(lap_time) as best_lap,
                                   array_agg(lap_time order by lap_time) as lap_times
                            from laps
                            group by team_number, stint, kart)
            select *,
                   (select avg(m) from unnest(lap_times[:laps_amount * 0.8]) m) as avg_80,
                   (select avg(m) from unnest(lap_times[:laps_amount * 0.4]) m) as avg_40
                   from stints
                )
            """,
            reverse_sql="drop materialized view stints info"
        )
    ]
