# Generated by Django 4.0.6 on 2022-07-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lap',
            name='sector_1',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lap',
            name='sector_2',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
