# Generated by Django 4.0.6 on 2023-06-08 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RacePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'race_passes',
            },
        ),
        migrations.AddField(
            model_name='race',
            name='allowed_users',
            field=models.ManyToManyField(related_name='allowed_races', through='stats.RacePass', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='racepass',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.race'),
        ),
        migrations.AddField(
            model_name='racepass',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='racepass',
            unique_together={('race', 'user')},
        ),
    ]
