# Generated by Django 4.0.6 on 2023-06-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_racepass_race_allowed_users_racepass_race_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='kart_overrides',
            field=models.JSONField(default=dict),
        ),
    ]
