# Generated by Django 4.0.6 on 2023-06-11 21:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_race_kart_overrides'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stint',
            fields=[
                ('stint_id', models.TextField(primary_key=True, serialize=False)),
                ('race_id', models.TextField()),
                ('pilot', models.TextField()),
                ('team', models.IntegerField()),
                ('stint', models.IntegerField()),
                ('kart', models.IntegerField()),
                ('stint_started_at', models.IntegerField()),
                ('laps_amount', models.IntegerField()),
                ('lap_times', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('best_lap', models.FloatField()),
                ('best_sector_1', models.FloatField()),
                ('best_sector_2', models.FloatField()),
                ('best_theoretical', models.FloatField()),
                ('avg_80', models.FloatField()),
            ],
            options={
                'db_table': 'stints',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='StintInfo',
        ),
        migrations.AlterField(
            model_name='boardrequest',
            name='response_json',
            field=models.JSONField(default=dict),
        ),
    ]
