# Generated by Django 4.0.6 on 2023-06-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_stint_delete_stintinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='racepass',
            name='accents',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='racepass',
            name='badges',
            field=models.JSONField(default=dict),
        ),
    ]
