# Generated by Django 4.0.6 on 2023-04-24 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_racelaunch_delete_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardrequest',
            name='race',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='stats.racelaunch', verbose_name='requests'),
            preserve_default=False,
        ),
    ]
