# Generated by Django 4.0.6 on 2023-04-24 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_boardrequest_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='lap',
            name='race',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='laps', to='stats.racelaunch'),
            preserve_default=False,
        ),
    ]
