# Generated by Django 4.0.6 on 2023-05-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_lap_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='racelaunch',
            name='skip_first_stint',
            field=models.BooleanField(default=False),
        ),
    ]
