# Generated by Django 4.0.6 on 2023-06-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_racepass_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racepass',
            name='accents',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='racepass',
            name='badges',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='racepass',
            name='notes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
