# Generated by Django 4.0.6 on 2023-05-19 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_racelaunch_skip_first_stint'),
    ]

    operations = [
        migrations.DeleteModel('Team'),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.TextField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='stats.racelaunch')),
            ],
            options={
                'db_table': 'teams',
            },
        ),
    ]
