# Generated by Django 4.0.6 on 2023-06-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_alter_racepass_accents_alter_racepass_badges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='racepass',
            name='show_first_stint',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
