# Generated by Django 4.0.6 on 2023-05-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='lap',
            name='lap_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
