# Generated by Django 4.0.6 on 2023-06-23 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_racestate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racepass',
            name='show_first_stint',
        ),
    ]
