# Generated by Django 4.0.6 on 2026-08-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_race_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrefillOptions',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('api_urls', models.JSONField(default=list)),
                ('race_lengths', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'prefill_options',
            },
        ),
        migrations.AddConstraint(
            model_name='prefilloptions',
            constraint=models.CheckConstraint(check=models.Q(('id', 1)), name='prefill_options_singleton_id'),
        ),
    ]
