# Generated by Django 4.0.6 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_prefilloptions_alter_race_kart_overrides_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='api_url',
            field=models.CharField(
                default='https://nfs-stats.herokuapp.com/getmaininfo.json',
                max_length=2048,
            ),
        ),
    ]
